name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./src
        run: |
          pip install poetry
          poetry install

      - name: Start FastAPI
        working-directory: ./src
        run: |
          poetry run uvicorn app:app --host 0.0.0.0 --port 8000 &

      - name: Run tests and Publish Test Report
        working-directory: ./src
        env:
          BACKEND_CORS_ORIGINS: '["*"]'
        run: |
          sleep 5  # Wait a bit for the server to be fully up and running
          poetry run pytest ./test/ --junitxml=./logs/pytest_report.xml || true
          echo "Publishing Test Report"
          curl -sSL https://github.com/dorny/test-reporter/releases/latest/download/test-reporter-linux -o test-reporter
          chmod +x test-reporter
          ./test-reporter -n 'Test Report' -p './logs/pytest_report.xml' -r 'java-junit' || true
