name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./src
        run: |
          pip install poetry
          poetry install

      - name: Run tests (inside Docker)
        working-directory: ./src
        run: pytest ./test/ --junitxml=/pytest_report.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: failure()
        with:
          report_paths: '/pytest_report.xml'
