name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: ./src
        run: |
          pip install poetry
          poetry install

      - name: Start FastAPI
        working-directory: ./src
        run: |
          poetry run uvicorn app:app --host 0.0.0.0 --port 8000 &

      - name: Run tests
        working-directory: ./src
        env:
          BACKEND_CORS_ORIGINS: '["*"]'
        run: |
          sleep 5  # Wait a bit for the server to be fully up and running
          poetry run pytest ./test/ --junitxml=./logs/pytest_report.xml

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: 'Test Report'
          path: './src/logs/pytest_report.xml'
          reporter: 'java-junit'
          fail-on-error: false