name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/checkout@v2

      - name: Move to python workspace
        run: cd src

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install poetry

      - name: Setup poetry project
        run: poetry install

      - name: Run tests (inside Docker)
        run: |
          pytest src/test --junitxml=pytest_report.xml
        continue-on-error: true


      - name: Install Node.js and xml2js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install xml2js
        run: |
          npm install xml2js

      - name: Report test results
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const xml2js = require('xml2js');
            const core = require('@actions/core');
            const parser = new xml2js.Parser();
            const xml = fs.readFileSync('src/pytest_report.xml', 'utf8');
            parser.parseString(xml, (err, result) => {
              if (err) {
                core.setFailed('Failed to parse XML');
                return;
              }
              const failures = result.testsuite.testcase.filter(tc => tc.failure);
              let commentBody = '## :x: Tests failed\n';
              failures.forEach(tc => {
                commentBody += `### ${tc.$.classname}::${tc.$.name}\n`;
                commentBody += `\`\`\`\n${tc.failure[0]._}\n\`\`\`\n`;
              });
              github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            });
